shared:
  api_url: <%= ENV["MEWST_API_URL"] %>
  email_domain: <%= ENV["MEWST_EMAIL_DOMAIN"] %>
  internal_api_token: <%= ENV["MEWST_INTERNAL_API_TOKEN"] %>
  redis_url: <%= ENV["REDIS_URL"] %>
  resend_api_key: <%= ENV["MEWST_RESEND_API_KEY"] %>
  sentry_dsn: <%= ENV["MEWST_SENTRY_DSN"] %>
  web_url: <%= ENV["MEWST_WEB_URL"] %>
